version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    target_branch: "security-patch"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

